-- Create blog posts table
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  body TEXT NOT NULL,
  excerpt TEXT,
  tags TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create static pages table
CREATE TABLE IF NOT EXISTS pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  meta_title TEXT,
  meta_description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  body TEXT NOT NULL,
  image TEXT,
  tags TEXT[] DEFAULT '{}',
  github_url TEXT,
  live_url TEXT,
  featured BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create a function to update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers to automatically update updated_at
CREATE TRIGGER update_posts_updated_at
  BEFORE UPDATE ON posts
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER update_pages_updated_at
  BEFORE UPDATE ON pages
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at();

CREATE TRIGGER update_projects_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW
  EXECUTE PROCEDURE update_updated_at();

-- Add sample data to posts
INSERT INTO posts (title, slug, body, excerpt, tags)
VALUES
  (
    'Getting Started with Next.js and Supabase',
    'getting-started-with-nextjs-and-supabase',
    '# Getting Started with Next.js and Supabase\n\nNext.js and Supabase are a powerful combination for building modern web applications. In this post, we''ll explore how to set them up and create a basic application.',
    'Learn how to build a modern web application using Next.js and Supabase as the backend.',
    ARRAY['Next.js', 'Supabase', 'Web Development']
  ),
  (
    'Building Responsive UIs with Tailwind CSS',
    'building-responsive-uis-with-tailwind-css',
    '# Building Responsive UIs with Tailwind CSS\n\nTailwind CSS has revolutionized how developers approach UI design. Here''s how to get started and build responsive interfaces.',
    'Discover how to create beautiful responsive interfaces quickly using Tailwind CSS.',
    ARRAY['CSS', 'Tailwind', 'Frontend']
  );

-- Add sample data to pages
INSERT INTO pages (slug, title, body, meta_title, meta_description)
VALUES
  (
    'about',
    'About Me',
    '# About Me\n\nHello! I''m Caden Burleson, a web developer and designer passionate about creating elegant and functional web experiences.',
    'About Caden Burleson | Developer & Designer',
    'Learn more about Caden Burleson, a web developer and designer focused on creating modern digital experiences.'
  ),
  (
    'contact',
    'Contact',
    '# Get in Touch\n\nInterested in working together? Feel free to reach out using the contact details below.',
    'Contact Caden Burleson',
    'Get in touch with Caden Burleson for web development and design projects.'
  );

-- Add sample data to projects
INSERT INTO projects (title, slug, description, body, tags, github_url, live_url, featured)
VALUES
  (
    'Project One',
    'project-one',
    'A short description of the first project.',
    '# Project One\n\nDetailed description of Project One and its features.',
    ARRAY['Next.js', 'React', 'Tailwind CSS'],
    'https://github.com/cadenburleson/project-one',
    'https://project-one.demo',
    true
  ),
  (
    'Project Two',
    'project-two',
    'A short description of the second project.',
    '# Project Two\n\nDetailed description of Project Two and its features.',
    ARRAY['Node.js', 'Express', 'MongoDB'],
    'https://github.com/cadenburleson/project-two',
    'https://project-two.demo',
    true
  ); 